### ISSUE TITLE
Error getting part data: Fingerprint was not found…

### ISSUE THREAD

**Issue by disjunto** [copy-app/php-client-library#21]
Currently unable to read file that exists beneath a company

**Comment by marphi** [comment]
I have the same issue with API.
Guys from copy.com do you have plan to fix this bug?

**Comment by ablyler** [comment]
@marphi / @disjunto: does passing in the share id of the file into the `getPart()` method fix it?

**Comment by marphi** [comment]
@ablyler It works! Thx!

I've changed this line https://github.com/copy-app/php-client-library/blob/master/src/API.php#L181 to:
```
$data = $this->getPart($part->{"fingerprint"}, $part->{"size"}, $file->{"share_id"});
```

**Comment by marphi** [comment]
I'll prepare PR with fix

**Comment by ablyler** [comment]
Thanks!  Merged.
