### ISSUE TITLE
Curl failed to exec SSL certificate

### ISSUE THREAD

**Issue by dzasa** [copy-app/php-client-library#23]
Hey,

I am having problems uploading file. I have set credentials but problems comes with curl and SSL:

PHP Fatal error:  Uncaught exception 'Exception' with message 'Curl failed to exec SSL certificate problem: unable to get local issuer certificate' in ../vendor/barracuda/copy/src/API.php:62

I am running this on Mac OS X Yosemite, php built with Brew 5.5.20

Best :)

**Comment by JasonDictos** [comment]
Looks like we need to update the ca bundle, you can try updating it by hand
from curls website here:
https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt

**Comment by dzasa** [comment]
That did fix the problem, first file sent over API :)
